@startuml
actor     Employer            as e
entity    VacancyManager      as vm
entity    VacancyRepository   as vr
database  Database            as db

e --> vm  : create/edit/delete vacancy
vm --> vr : create/edit/delete vacancy in DB
vr --> db
vr <-- db
vm <-- vr : operation response
e <-- vm
@enduml
